package com.alag.agbao.business.packet.api.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class RedAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_red_packet_account.id
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_red_packet_account.amount
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_red_packet_account.user_id
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_red_packet_account.version
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_red_packet_account.id
     *
     * @return the value of red_red_packet_account.id
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_red_packet_account.id
     *
     * @param id the value for red_red_packet_account.id
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_red_packet_account.amount
     *
     * @return the value of red_red_packet_account.amount
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_red_packet_account.amount
     *
     * @param amount the value for red_red_packet_account.amount
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_red_packet_account.user_id
     *
     * @return the value of red_red_packet_account.user_id
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_red_packet_account.user_id
     *
     * @param userId the value for red_red_packet_account.user_id
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_red_packet_account.version
     *
     * @return the value of red_red_packet_account.version
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_red_packet_account.version
     *
     * @param version the value for red_red_packet_account.version
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}