package com.alag.agbao.business.captical.server.mapper;

import com.alag.agbao.business.captical.api.model.CapAccount;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;

@Mapper
public interface CapAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_capital_account
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_capital_account
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    int insert(CapAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_capital_account
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    int insertSelective(CapAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_capital_account
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    CapAccount selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_capital_account
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    int updateByPrimaryKeySelective(CapAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_capital_account
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    int updateByPrimaryKey(CapAccount record);

    int updateByIdAndVersion(@Param("accountId") String accountId, @Param("version") Integer version, @Param("amount") BigDecimal afterAmount);
}