package com.alag.agbao.business.captical.server.mapper;

import com.alag.agbao.business.captical.api.model.CapTradeOrder;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CapTradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_trade_order
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_trade_order
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    int insert(CapTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_trade_order
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    int insertSelective(CapTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_trade_order
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    CapTradeOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_trade_order
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    int updateByPrimaryKeySelective(CapTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cap_trade_order
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    int updateByPrimaryKey(CapTradeOrder record);
}