package com.alag.agbao.business.packet.server.mapper;

import com.alag.agbao.business.packet.api.model.RedAccount;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;

@Mapper
public interface RedAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_red_packet_account
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_red_packet_account
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    int insert(RedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_red_packet_account
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    int insertSelective(RedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_red_packet_account
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    RedAccount selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_red_packet_account
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    int updateByPrimaryKeySelective(RedAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_red_packet_account
     *
     * @mbggenerated Fri Aug 23 20:22:12 CST 2019
     */
    int updateByPrimaryKey(RedAccount record);

    RedAccount selectByUserId(String userId);

    int updateByIdAndVersion(@Param("id") String id, @Param("version") Integer version, @Param("amount") BigDecimal amount);
}