package com.alag.agbao.business.packet.server.mapper;

import com.alag.agbao.business.packet.api.model.RedTradeOrder;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface RedTradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_trade_order
     *
     * @mbggenerated Fri Aug 23 15:42:53 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_trade_order
     *
     * @mbggenerated Fri Aug 23 15:42:53 CST 2019
     */
    int insert(RedTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_trade_order
     *
     * @mbggenerated Fri Aug 23 15:42:53 CST 2019
     */
    int insertSelective(RedTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_trade_order
     *
     * @mbggenerated Fri Aug 23 15:42:53 CST 2019
     */
    RedTradeOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_trade_order
     *
     * @mbggenerated Fri Aug 23 15:42:53 CST 2019
     */
    int updateByPrimaryKeySelective(RedTradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_trade_order
     *
     * @mbggenerated Fri Aug 23 15:42:53 CST 2019
     */
    int updateByPrimaryKey(RedTradeOrder record);
}