package com.alag.agbao.business.captical.api.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class CapAccount implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_capital_account.account_id
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_capital_account.amount
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_capital_account.version
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_capital_account.account_id
     *
     * @return the value of cap_capital_account.account_id
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_capital_account.account_id
     *
     * @param accountId the value for cap_capital_account.account_id
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_capital_account.amount
     *
     * @return the value of cap_capital_account.amount
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_capital_account.amount
     *
     * @param amount the value for cap_capital_account.amount
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_capital_account.version
     *
     * @return the value of cap_capital_account.version
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_capital_account.version
     *
     * @param version the value for cap_capital_account.version
     *
     * @mbggenerated Fri Aug 23 20:17:55 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}