package com.alag.agbao.business.captical.api.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.function.Function;


public class CapTradeOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_trade_order.id
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_trade_order.user_id
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_trade_order.order_no
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_trade_order.amount
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cap_trade_order.status
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_trade_order.id
     *
     * @return the value of cap_trade_order.id
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_trade_order.id
     *
     * @param id the value for cap_trade_order.id
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_trade_order.user_id
     *
     * @return the value of cap_trade_order.user_id
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_trade_order.user_id
     *
     * @param userId the value for cap_trade_order.user_id
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_trade_order.order_no
     *
     * @return the value of cap_trade_order.order_no
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_trade_order.order_no
     *
     * @param orderNo the value for cap_trade_order.order_no
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_trade_order.amount
     *
     * @return the value of cap_trade_order.amount
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_trade_order.amount
     *
     * @param amount the value for cap_trade_order.amount
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cap_trade_order.status
     *
     * @return the value of cap_trade_order.status
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cap_trade_order.status
     *
     * @param status the value for cap_trade_order.status
     *
     * @mbggenerated Fri Aug 23 15:49:52 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    public static CapTradeOrder setReturn(Function<CapTradeOrder, CapTradeOrder> function) {
        return function.apply(new CapTradeOrder());
    }
}