package com.alag.agbao.business.order.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.id
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.order_no
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.user_id
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.payment
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private BigDecimal payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.status
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.payment_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.create_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ord_order.update_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.id
     *
     * @return the value of ord_order.id
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.id
     *
     * @param id the value for ord_order.id
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.order_no
     *
     * @return the value of ord_order.order_no
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.order_no
     *
     * @param orderNo the value for ord_order.order_no
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.user_id
     *
     * @return the value of ord_order.user_id
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.user_id
     *
     * @param userId the value for ord_order.user_id
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.payment
     *
     * @return the value of ord_order.payment
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.payment
     *
     * @param payment the value for ord_order.payment
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.status
     *
     * @return the value of ord_order.status
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.status
     *
     * @param status the value for ord_order.status
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.payment_time
     *
     * @return the value of ord_order.payment_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.payment_time
     *
     * @param paymentTime the value for ord_order.payment_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.create_time
     *
     * @return the value of ord_order.create_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.create_time
     *
     * @param createTime the value for ord_order.create_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ord_order.update_time
     *
     * @return the value of ord_order.update_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ord_order.update_time
     *
     * @param updateTime the value for ord_order.update_time
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}