package com.alag.agbao.business.order.mapper;

import com.alag.agbao.business.order.model.Order;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_order
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_order
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_order
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_order
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_order
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ord_order
     *
     * @mbggenerated Fri Aug 23 15:46:51 CST 2019
     */
    int updateByPrimaryKey(Order record);

    Order selectByOrderId(String orderNo);
}